### ISSUE TITLE
Add logout to select church screen.

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AppBase#146]
After a user logs in, they get a list of churches.  Sometimes a user may have multiple accounts and accidentally logged into the wrong one.  There's no way to abort the login process once you get this prompt.  Even refreshing the page doesn't work due to the cookie.  Add a logout option to the select a church pop-up

**Comment by PhotoPaul** [comment]
I pushed a change that takes care of this by adding a `closeButton` to the SelectChurch Modal and also by allowing keyboard events (so the ESC key can also be used to the same effect).

The "proper" fix would have been to use `setShowSearch(false);` to hide the Modal and then reset the login form (i.e. empty the input fields, re-enable the login button etc.). However this line didn't work to hide the modal and I was unable to figure out why.

Due to the reasons explained above, I opted for fully refreshing the page using `window.location.reload();` since I couldn't replicate the problem you're describing due to the authorization cookie.

**Comment by jzongker** [comment]
I'm not seeing the authorization cookie problem at the moment either.  I think this approach will work, and really like the simpler route of just adding the closeButton.

The "showSearch" toggle switches the model to the Search for a Church view whenever you click the Add church button.  It's already false by default until you click that add link, so that's why changing it didn't do anything.  The "proper" way would be to call setShowSelectModal(false) in the parent LoginPage.tsx by raising an cancel event from SelectChurchModal  and handling it in LoginPage.  I think this reload is fine though.
